apiVersion: v1
kind: Service
metadata:
  name: just-chat-api-service
spec:
  type: NodePort
  selector:
    service: just-chat-api
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 9000
